layout_spectrum: 0.3284123
typography_spectrum: 0.3033691
color:
  saturation: 0.02162867
  lightness: 0.6864192
  brandStrength: 0.8374392
  rhythmicContrast: 0.1835939
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Eliottest
